name: deploy

on:
  workflow_call:
    inputs:
      IMAGE_LABEL:
        description: Image Label to deploy
        type: string
        default: latest
      DEPLOY_DEV_1:
        description: Deploy to dev1
        type: boolean
        default: true
      DEPLOY_DEV_2:
        description: Deploy to dev2
        type: boolean
        default: false
      DEPLOY_STAGING_1:
        description: Deploy to staging1
        type: boolean
        default: false
      DEPLOY_STAGING_2:
        description: Deploy to staging2
        type: boolean
        default: false
      DEPLOY_STAGING_3:
        description: Deploy to staging3
        type: boolean
        default: false
      DEPLOY_PROD_1:
        description: Deploy to prod1
        type: boolean
        default: false

  workflow_dispatch:
    inputs:
      IMAGE_LABEL:
        description: Image Label to deploy
        type: string
        default: latest
      DEPLOY_DEV_1:
        description: Deploy to dev1
        type: boolean
        default: true
      DEPLOY_DEV_2:
        description: Deploy to dev2
        type: boolean
        default: false
      DEPLOY_STAGING_1:
        description: Deploy to staging1
        type: boolean
        default: false
      DEPLOY_STAGING_2:
        description: Deploy to staging2
        type: boolean
        default: false
      DEPLOY_STAGING_3:
        description: Deploy to staging3
        type: boolean
        default: false
      DEPLOY_PROD_1:
        description: Deploy to prod1
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  dev-1-deployment:
    if: ${{ input.DEPLOY_DEV_1 }}
    uses: ./.github/workflows/do-deploy.yml
    with:
      ENVIRONMENT: dev-1
      IMAGE_LABEL: ${{ input.IMAGE_LABEL }}
  dev-2-deployment:
    if: ${{ input.DEPLOY_DEV_2 }}
    uses: ./.github/workflows/do-deploy.yml
    with:
      ENVIRONMENT: dev-2
      IMAGE_LABEL: ${{ input.IMAGE_LABEL }}
  staging-1-deployment:
    if: ${{ input.DEPLOY_STAGING_1 }}
    uses: ./.github/workflows/do-deploy.yml
    with:
      ENVIRONMENT: staging-1
      IMAGE_LABEL: ${{ input.IMAGE_LABEL }}
  staging-2-deployment:
    if: ${{ input.DEPLOY_STAGING_2 }}
    uses: ./.github/workflows/do-deploy.yml
    with:
      ENVIRONMENT: staging-2
      IMAGE_LABEL: ${{ input.IMAGE_LABEL }}
  staging-3-deployment:
    if: ${{ input.DEPLOY_STAGING_3 }}
    uses: ./.github/workflows/do-deploy.yml
    with:
      ENVIRONMENT: staging-3
      IMAGE_LABEL: ${{ input.IMAGE_LABEL }}
  prod-1-deployment:
    if: ${{ input.DEPLOY_PROD_1 }}
    uses: ./.github/workflows/do-deploy.yml
    with:
      ENVIRONMENT: prod-1
      IMAGE_LABEL: ${{ input.IMAGE_LABEL }}
