name: release deployment

on:
  push:
    tags:
      - '*'

jobs:
  release-deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      IMAGE_LABEL: ${{ github.ref }}
      DEPLOY_DEV_1: true
      DEPLOY_DEV_2: true
      DEPLOY_STAGING_1: true
      DEPLOY_STAGING_2: true
      DEPLOY_STAGING_3: true
      DEPLOY_PROD_1: true