name: Perform Deploy

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        description: Environment to deploy to
        type: string
        required: true
      IMAGE_LABEL:
        description: Image Label to deploy
        type: string
        default: latest
      SERVICE_NAME:
        description: The service to deploy
        type: string
        required: true

permissions:
  contents: read

env:
  ENV_MAPPING_DICT: '{
    "dev-1": {
      "service-name": {
        "image-name": "dev1"
      }
    },
    "dev-2": {
       "service-name": { 
        "image-name": "dev2"
      }
    },
    "staging-1": {
      "service-name": {
        "image-name": "staging1"
      }
    },
    "staging-2": {
      "service-name": {
        "image-name": "staging2"
      }
    },
    "staging-3": {
    "service-name": {
      "image-name": "staging3"
      }
    },
    "prod-1": {
    "service-name": {
      "image-name": "el production"
      }
    }
  }'

jobs:
  deployment:
    name: Deploy to ${{ inputs.ENVIRONMENT }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: Say hello
        run: "echo Hello from ${{inputs.ENVIRONMENT}} - my image is: ${{ fromJSON(env.ENV_MAPPING_DICT)[inputs.ENVIRONMENT].[inputs.serviceName].image-name }} and I am deploying ${{ inputs.IMAGE_LABEL }}"
